### PR TITLE
[PAGOPA 353] Azure DevOps deploy pipeline migration and check - Pipeline Migration

### PR DESCRIPTION
**Pull request by AngeloCaporaso**
This pull request includes all the changes related to the update made on Azure DevOps pipeline for the deploy and related support stages. Before this PR, the pipeline was not configured correctly and the pipeline files were the same as the model whose project was cloned.

#### List of Changes

- Smoke test stage updates with DEV and UAT env variables
- Integration test stage updates with DEV and UAT env variables
- Helm values adaptation to enable deploy stage
- Integration test automation in `run_integration_test.sh`
- Docker environment configuration updating

#### Motivation and Context

These changes are necessary because deploy's pipeline was not working properly at all in the context of dedicated repository.

#### How Has This Been Tested?

Firstly from local via helm package manager then on azure devops pipeline through manual trigger.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by FedericoRuzzier — APPROVED** [review]
LGTM 💯

**Review by andrea-deri — APPROVED** [review]
Very good!

**Review by aomegax — APPROVED** [review]
👍

**Review by aomegax — APPROVED** [review]
👍

**Pull request merged**
