### PR TITLE
[PAGOPA-1359] fix: Update partially PAID case

### PR DESCRIPTION
**Pull request by AngeloCaporaso**
#### List of Changes

`checkDebtPositionStatus` is called in `paVerifyPaymentNotice` and `manageGetPaymentRequest`.

The method `checkDebtPositionStatus` has been updated so that a _payment position_ in `PARTIALLY_PAID` state does not generate a `PAGAMENTO_DUPLICATO` type exception. Specifically, the condition is replaced through a check on the _payment option_ state, that is, the _payment option_ must not be in state `PO_PAID`.

Add check on `PAA_PAGAMENTO_SCADUTO` exception: when _Payment Option_ `dueDate` has been passed the payment is considered overdue.

#### Motivation and Context

Fix check on `paVerifyPaymentNotice` SOAP action.

#### How Has This Been Tested?

Local environment (gpd-payments) versus DEV instances (pgsql, gpd-core).
Integration test in UAT environment.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by alessio-acitelli — APPROVED** [review]
OK 👍

**Review by alessio-acitelli — COMMENTED** [review]
fix junit and smoke before merge

**Comment by AngeloCaporaso** [comment]
update_code

**Review by FedericoRuzzier — APPROVED** [review]
LGTM 👍

**Pull request merged**
